In [1]:
# 1- D
# 2-D
# 3-D


# Create array
# 

# 1-D


In [5]:
# Create array
import pandas as pd
import numpy as np


In [6]:

a = np.array([1,2,3,4])           
a

array([1, 2, 3, 4])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [22]:
b = np.arange(6,2)
b

array([], dtype=int32)

In [24]:
np.empty(3)

array([1.48949894e-311, 0.00000000e+000, 6.47591605e-319])

In [26]:
# Create linearly spaced array which has equal difference

np.linspace(5,10,3)

array([ 5. ,  7.5, 10. ])

# 2-D

In [29]:
x = np.array([[1,2,3],[4,5,6]])

In [51]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
x.ndim

2

In [35]:
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
x.shape

(2, 3)

In [37]:
np.shape(x)

(2, 3)

In [52]:
x[: , np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [53]:
x[np.newaxis, :]

array([[[1, 2, 3],
        [4, 5, 6]]])

# 3-D

In [41]:
k = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])

In [42]:
k.ndim

3

In [43]:
k.shape

(1, 3, 3)

In [45]:
k

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
k[np.newaxis, :]

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [54]:
z = np.array([1,2,3,4,5,6])

In [55]:
z.shape

(6,)

In [56]:
z.ndim

1

In [57]:
z

array([1, 2, 3, 4, 5, 6])

In [60]:
zz = z[ : , np.newaxis]

In [61]:
zz.shape

(6, 1)

In [62]:
zz.ndim

2